databases:
  - name: touhoku_DB
    databaseName:  touhoku_db
    user: touhoku
    region: singapore

services:
  - type: web
    name: touhoku
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: touhoku_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

